package com.tnsif.exceptionhandling;

public class Withexception {
int d=0;
try
{
	int a=5/0;
}
catch(Arithematic Exception e) {
	System.out.println("Exception caught"+e);
	System.out.println("Exception caught"+e);
}
}
